name: Personal site cron job
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  cron:
    run-on: ubuntu-latest
    steps:
      - name: Hit site to refresh cache
        run: |
          curl https://www.kylevb.com/anime
